#!/usr/bin/env bash
# Move package to local folder
mv cp -r template/template ~/Library/Application\ Support/typst/packages/local/dhbw-oderso/2.0.1
mv cp -r typst.toml ~/Library/Application\ Support/typst/packages/local/dhbw-oderso/2.0.1